[bundle]
separators = true
deterministic = false
output = "test/frob/final.c"

[header]
enable = true
text = """
// My amazing header text!
"""
#source = "header.txt"

[banner]
enable = true

[banner.quote]
enable = true
pick = "custom"

[formatter]
enable = true
path = "clang-format"
args = ["--verbose", "--sort-includes"]

[[quote]]
text = """
Use a gun. And if that don't work...
                                      use more gun.
"""
author = "Dr. Dell Conagher"

[[quote]]
text = "Democracy prevails once more."
author = "Democracy Officer"
